apiVersion: apps/v1
kind: Deployment
metadata:
  name: edi-alpha
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edi-alpha
  template:
    metadata:
      labels:
        app: edi-alpha
    spec:
      containers:
        - name: edi-alpha
          image: nginx:alpine
          ports:
            - containerPort: 80
