apiVersion: apps/v1
kind: Deployment
metadata:
  name: beta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beta
  template:
    metadata:
      labels:
        app: beta
    spec:
      containers:
        - name: beta
          image: nginx:alpine
          ports:
            - containerPort: 80
